#!/usr/bin/env python3
"""Sync a shared education sheet into _data/education_courses.yml.

The script accepts either:
- a local CSV file, or
- a Google Sheets URL / published CSV URL

It mirrors remote CSV content back into shared/education_sheet.csv so the
Google Sheet can remain the source of truth.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import re
import sys
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = ROOT / "shared" / "education_sync.json"
DEFAULT_SOURCE = ROOT / "shared" / "education_sheet.csv"
DEFAULT_OUTPUT = ROOT / "_data" / "education_courses.yml"
USER_AGENT = "ArcoLabEducationSync/1.0 (arcolabucbm@gmail.com)"

REQUIRED_COLUMNS = {
    "status",
    "title",
    "degree_program",
    "cfu",
    "description",
    "holder",
    "assistants",
    "year",
    "term",
}


def log(message: str) -> None:
    print(message, file=sys.stderr)


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def normalize_google_sheet_source(source: str) -> str:
    source = normalize_space(source)
    if not source.startswith("https://docs.google.com/spreadsheets/d/"):
        return source
    if "output=csv" in source or "/gviz/tq?" in source:
        return source

    match = re.search(r"/spreadsheets/d/([a-zA-Z0-9-_]+)", source)
    if not match:
        return source

    spreadsheet_id = match.group(1)
    gid_match = re.search(r"[?#&]gid=([0-9]+)", source)
    gid = gid_match.group(1) if gid_match else "0"
    return (
        "https://docs.google.com/spreadsheets/d/"
        f"{spreadsheet_id}/export?format=csv&gid={gid}"
    )


def yaml_quote(value: str) -> str:
    value = str(value)
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def split_list(value: str) -> list[str]:
    if not value:
        return []
    parts = [normalize_space(part) for part in value.split(";")]
    return [part for part in parts if part]


def load_rows(source: str, mirror_path: Path | None = None) -> list[dict[str, str]]:
    source = normalize_google_sheet_source(source)
    if re.match(r"^https?://", source):
        request = urllib.request.Request(source, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(request, timeout=20) as response:
            raw = response.read().decode("utf-8-sig")
        if mirror_path is not None:
            mirror_path.write_text(raw, encoding="utf-8")
    else:
        raw = Path(source).read_text(encoding="utf-8-sig")

    reader = csv.DictReader(io.StringIO(raw))
    if reader.fieldnames is None:
        raise ValueError("The education sheet is empty or missing a header row.")

    fieldnames = {name.strip() for name in reader.fieldnames if name}
    missing = REQUIRED_COLUMNS - fieldnames
    if missing:
        raise ValueError("Missing required CSV columns: " + ", ".join(sorted(missing)))

    rows: list[dict[str, str]] = []
    for row in reader:
        cleaned = {
            key.strip(): normalize_space(value)
            for key, value in row.items()
            if key
        }
        if any(cleaned.values()):
            rows.append(cleaned)
    return rows


def write_yaml(courses: list[dict[str, str]], destination: Path) -> None:
    lines = [
        "# This file is generated by scripts/sync_education.py from shared/education_sheet.csv.",
        "# Manual edits will be overwritten the next time the sync script runs.",
    ]

    for course in courses:
        assistants = split_list(course.get("assistants", ""))
        lines.append(f"- title: {yaml_quote(course.get('title', ''))}")
        lines.append(f"  degree_program: {yaml_quote(course.get('degree_program', ''))}")
        lines.append(f"  cfu: {yaml_quote(course.get('cfu', ''))}")
        lines.append(f"  description: {yaml_quote(course.get('description', ''))}")
        lines.append(f"  holder: {yaml_quote(course.get('holder', ''))}")
        lines.append(f"  year: {yaml_quote(course.get('year', ''))}")
        lines.append(f"  term: {yaml_quote(course.get('term', ''))}")
        if assistants:
            lines.append("  assistants:")
            for assistant in assistants:
                lines.append(f"    - {yaml_quote(assistant)}")
        else:
            lines.append("  assistants: []")

    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default="", help="Path to a local CSV or Google Sheet URL.")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG), help="JSON config file with the shared Google Sheet URL.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Target YAML file. Defaults to _data/education_courses.yml.")
    args = parser.parse_args()

    config = load_config(Path(args.config))
    source = normalize_space(args.source) or normalize_space(str(config.get("source", ""))) or str(DEFAULT_SOURCE)
    normalized_source = normalize_google_sheet_source(source)
    mirror_path = DEFAULT_SOURCE if re.match(r"^https?://", normalized_source) else None
    rows = load_rows(source, mirror_path=mirror_path)

    courses: list[dict[str, str]] = []
    for row in rows:
        status = normalize_space(row.get("status", "")).lower()
        if status in {"draft", "ignore", "skip"}:
            continue
        courses.append(
            {
                "title": row.get("title", ""),
                "degree_program": row.get("degree_program", ""),
                "cfu": row.get("cfu", ""),
                "description": row.get("description", ""),
                "holder": row.get("holder", ""),
                "assistants": row.get("assistants", ""),
                "year": row.get("year", ""),
                "term": row.get("term", ""),
            }
        )

    courses.sort(key=lambda item: (item.get("year", ""), item.get("title", "")), reverse=True)
    output = Path(args.output)
    write_yaml(courses, output)
    print(f"Wrote {len(courses)} education entries to {output} from {source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
